version: "3"
services:
  graphql-postgres:
    image: "postgres"
    container_name: "graphql-postgres"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=graphql-db

  flyway_db:
    image: "boxfuse/flyway"
    container_name: "graphql-flyway"
    command: -url=jdbc:postgresql://graphql-postgres:5432/graphql-db -user=admin -password=password -connectRetries=10 migrate
    volumes:
      - ./docker/flyway/migration:/flyway/sql
    depends_on:
      - graphql-postgres
